app/questions/models.py
from datetime import datetime
from functools import partial

from sqlalchemy import Column

from app import db

NotNullColumn = partial(Column, nullable=False)


class Question(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    text = NotNullColumn(db.String(500))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    answers = db.relationship('Answer', backref='question', lazy='dynamic')

    created = db.Column(db.DateTime, default=datetime.now)

    def __repr__(self):
        return '<Question {}>'.format(self.text)


class Answer(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    text = NotNullColumn(db.String(1000))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    question_id = db.Column(db.Integer, db.ForeignKey('question.id'))
    created = db.Column(db.DateTime, default=datetime.now)

    def __repr__(self):
        return '<Answer {} on question {}>'.format(self.text, self.question_id)

app/questions/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms import validators


class QuestionForm(FlaskForm):
    class Meta:
        csrf = False

    text = StringField('Question',
                       validators=[validators.DataRequired()])


class AnswerForm(FlaskForm):
    class Meta:
        csrf = False

    text = StringField('Answer',
                       validators=[validators.DataRequired()])

app/questions/__init__.py
from flask import Blueprint

questions_page = Blueprint('questions_page', __name__)

from app.questions import routes

app/questions/routes.py
from flask import render_template, redirect, url_for
from flask import request

from . import questions_page
from .forms import QuestionForm, AnswerForm
from .models import Question, Answer
from .. import db
from ..user.utils import get_current_user


@questions_page.route('/', methods=['GET', 'POST'])
def questions():
    questions_lst = Question.query.all()
    return render_template('questions/questions.html',
                           questions=questions_lst,
                           )


@questions_page.route('/<question_id>', methods=['GET', 'POST'])
def question(question_id):
    question_item = Question.query.filter_by(id=question_id).first()
    return render_template('questions/question.html',
                           question=question_item)


@questions_page.route('/ask-question', methods=['GET', 'POST'])
def ask_question():
    form = QuestionForm(request.form)
    if request.method == 'POST' and form.validate():
        user = get_current_user()
        question = Question(
            text=form.text.data,
            user_id=user.id
        )
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('questions_page.questions'))
    return render_template('questions/ask.html',
                           form=form)


@questions_page.route('/answer-question/<question_id>', methods=['GET', 'POST'])
def answer_question(question_id):
    form = AnswerForm(request.form)
    question_item = Question.query.filter_by(id=question_id).first()
    if request.method == 'POST' and form.validate():
        user = get_current_user()
        answer = Answer(
            text=form.text.data,
            user_id=user.id,
            question_id=question_item.id
        )
        db.session.add(answer)
        db.session.commit()
        return redirect(url_for('questions_page.question',
                                question_id=question_item.id))
    return render_template('questions/answer.html',
                           form=form,
                           question=question_item)

app/templates/questions/answer.html
{% extends 'base.html' %}

{% block title %}
    Answer Question
{% endblock %}

{% block content %}
    <div class="container theme-showcase" role="main">

        <div class="page-header">
            <h1>{{ question.text }}</h1>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="well bs-component">
                    {% from '_formhelper.html' import render_field %}
                    <form method="POST" action="{{ url_for('questions_page.answer_question', question_id=question.id) }}">
                        {{ form.csrf_token }}
                        <fieldset>
                            {{ render_field(form.text, class="form-control", placeholder="Write an answer...") }}
                            <div class="form-group">
                                <div class="col-lg-10 col-lg-offset-2">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

app/templates/questions/ask.html
{% extends 'base.html' %}

{% block title %}
    Ask a Question
{% endblock %}

{% block content %}
    <div class="container theme-showcase" role="main">

        <div class="page-header">
            <h1>Ask a Question</h1>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="well bs-component">
                    {% from '_formhelper.html' import render_field %}
                    <form class="form-horizontal" method="POST" action="{{ url_for('questions_page.ask_question') }}">
                        <fieldset>
                            {{ form.csrf_token }}
                            <fieldset>
                                {{ render_field(form.text, class="form-control", placeholder="Write a question...") }}
                                <div class="form-group">
                                    <div class="col-lg-10 col-lg-offset-2">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </div>
                            </fieldset>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

app/templates/questions/question.html
{% extends 'base.html' %}

{% block title %}
    Question
{% endblock %}

{% block content %}
    <div class="container theme-showcase" role="main">

            <div class="jumbotron">
                <div>
                    <b>{{ question.text|upper }}</b>
                    <span>, Asked By: {{ question.user.name }}</span>
                    {% for answer in question.answers %}
                        <p>
                            {{ answer.text }}
                            <span>, Answered By: {{ answer.user.name }}</span>
                        </p>
                    {% endfor %}
                    <a href="{{ url_for('questions_page.answer_question', question_id=question.id) }}"
                       class="btn btn-primary">Answer</a>
                </div>
            </div>

    </div> <!-- /container -->
{% endblock %}

app/templates/questions/questions.html
{% extends 'base.html' %}

{% block title %}
    Questions
{% endblock %}

{% block content %}
    <div class="container theme-showcase" role="main">

        {% for question in questions %}
            <div class="jumbotron">
                <div>
                    <b>{{ question.text|upper }}</b>
                    <span>, Asked By: {{ question.user.name }}</span>
                    <a href="{{ url_for('questions_page.question', question_id=question.id) }}"
                       class="btn btn-primary">View Question</a>
                    <a href="{{ url_for('questions_page.answer_question', question_id=question.id) }}"
                       class="btn btn-primary">Answer</a>
                </div>
            </div>
        {% endfor %}
    </div> <!-- /container -->
{% endblock %}

app/templates/questions/unanswered.html
{% extends 'base.html' %}

{% block title %}
    Questions For You
{% endblock %}

{% block content %}
    <div class="container theme-showcase" role="main">

        <div class="page-header">
            <h1>Questions For You</h1>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="list-group">
                    <a href="#" class="list-group-item">
                        <h4 class="list-group-item-heading">Question One</h4>
                        <p class="list-group-item-text">Asked by: Herbert</p>
                    </a>
                    <a href="#" class="list-group-item">
                        <h4 class="list-group-item-heading">Question Two</h4>
                        <p class="list-group-item-text">Asked by: Herbert</p>
                    </a>
                    <a href="#" class="list-group-item">
                        <h4 class="list-group-item-heading">Question Three</h4>
                        <p class="list-group-item-text">Asked by: Herbert</p>
                    </a>
                </div>
            </div><!-- /.col-lg-12 -->
        </div>

    </div> <!-- /container -->
{% endblock %}