app/user/models.py
from datetime import datetime
from functools import partial

import bcrypt
from slugify import slugify
from sqlalchemy import Column

from app import db

NotNullColumn = partial(Column, nullable=False)


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = NotNullColumn(db.String(250))
    email = NotNullColumn(db.String, unique=True)
    password = NotNullColumn(db.String)
    created = db.Column(db.DateTime, default=datetime.now)

    answers = db.relationship('Answer', backref='user', lazy='dynamic')
    questions = db.relationship('Question', backref='user', lazy='dynamic')

    slug = db.Column(db.String(), nullable=True)

    def __repr__(self):
        return '<User {}>'.format(self.name)

    def __init__(self, *args, **kwargs):
        if 'slug' not in kwargs:
            kwargs['slug'] = slugify(kwargs.get('name', ''))
        super().__init__(*args, **kwargs)

    @staticmethod
    def make_password_hash(password):
        hash = bcrypt.hashpw(password=password.encode('utf-8'),
                             salt=bcrypt.gensalt())
        return hash.decode('utf-8')

    def is_password_valid(self, password):
        return bcrypt.checkpw(password.encode('utf-8'),
                              self.password.encode('utf-8'))

app/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms import validators
from wtforms.fields.html5 import EmailField


class RegisterForm(FlaskForm):
    class Meta:
        csrf = False

    name = StringField('Name',
                       validators=[validators.DataRequired(),
                                   validators.Length(min=2, max=80)])
    email = EmailField('Email',
                       validators=[validators.DataRequired(),
                                   validators.Email()])
    password = PasswordField('Password',
                             validators=[validators.DataRequired(),
                                         validators.EqualTo('confirm_password',
                                                            message='Password must match')])
    confirm_password = PasswordField('Confirm password',
                                     validators=[validators.DataRequired()])


class LoginForm(FlaskForm):
    class Meta:
        csrf = False

    email = EmailField('Email',
                       validators=[validators.DataRequired(),
                                   validators.Email()])
    password = PasswordField('Password',
                             validators=[validators.DataRequired()])

app/user/__init__.py
from flask import Blueprint

user_page = Blueprint('user_page', __name__)

from app.user import routes

app/user/routes.py
from flask import render_template, redirect, url_for
from flask import request
from flask import session

from . import user_page
from .forms import RegisterForm, LoginForm
from .models import User
from .. import db


@user_page.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST' and form.validate():
        name = form.name.data
        email = form.email.data
        password = form.password.data
        user = User(name=name,
                    email=email,
                    password=User.make_password_hash(password))
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('user_page.login'))
    return render_template('user/register.html',
                           form=form)


@user_page.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    error = None
    if request.method == 'POST' and form.validate():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.is_password_valid(form.password.data):
            session['user'] = user.email
            return redirect(url_for('index'))
        else:
            user = None
        if not user:
            error = 'Your email or password was entered incorrectly'
    return render_template('user/login.html',
                           form=form,
                           error=error)


@user_page.route('/logout')
def logout():
    session.pop('user')
    return redirect(url_for('user_page.login'))


@user_page.route('/users')
def users():
    users_lst = User.query.all()
    return render_template('user/users.html',
                           users=users_lst)

app/templates/_formhelper.html
{% macro render_field(field) %}
<div class="form-group">
    {{ field(**kwargs) | safe }}
    {% if field.errors %}
        <ul class="text-danger">
            {% for error in field.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
</div>
{% endmacro %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>
        {% block title %} Questions & Answers {% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">

    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
</head>

<body>

<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ url_for('index') }}">Questions & Answers</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{{ url_for('index') }}">Home</a></li>
                {% if not user %}
                <li><a href="{{ url_for('user_page.login') }}">Login</a></li>
                <li><a href="{{ url_for('user_page.register') }}">Register</a></li>
                {% endif %}
                {% if user %}
                    <li><a href="{{ url_for('questions_page.ask_question') }}">Ask Question</a></li>
                    <li><a href="{{ url_for('questions_page.questions') }}">Questions</a></li>
                    <li><a href="{{ url_for('user_page.users') }}">User Setup</a></li>
                    <li><a href="{{ url_for('user_page.logout') }}">Logout</a></li>
                {% endif %}
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

{% block content %}
    <div class="container theme-showcase" role="main">

        <div class="page-header">
            <h1>Answered Questions</h1>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="list-group">
                    <a href="#" class="list-group-item">
                        <h4 class="list-group-item-heading">Question One</h4>
                        <p class="list-group-item-text">Asked by: Herbert</p>
                        <p class="list-group-item-text">Answered by: Anthony</p>
                    </a>
                    <a href="#" class="list-group-item">
                        <h4 class="list-group-item-heading">Question Two</h4>
                        <p class="list-group-item-text">Asked by: Herbert</p>
                        <p class="list-group-item-text">Answered by: Anthony</p>
                    </a>
                    <a href="#" class="list-group-item">
                        <h4 class="list-group-item-heading">Question Three</h4>
                        <p class="list-group-item-text">Asked by: Herbert</p>
                        <p class="list-group-item-text">Answered by: Anthony</p>
                    </a>
                </div>
            </div><!-- /.col-lg-12 -->
        </div>

    </div> <!-- /container -->
{% endblock %}

</body>
</html>

app/templates/users.html
{% extends 'base.html' %}

{% block title %}
    Users
{% endblock %}

{% block content %}
    <div class="container theme-showcase" role="main">

        <div class="page-header">
            <h1>Users</h1>
            <h6>Click to promote to expert</h6>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="list-group">
                    <a href="#" class="list-group-item active">
                        <h4 class="list-group-item-heading">Admin</h4>
                    </a>
                    <a href="#" class="list-group-item">
                        <h4 class="list-group-item-heading">Herbert</h4>
                    </a>
                    <a href="#" class="list-group-item active">
                        <h4 class="list-group-item-heading">Anthony</h4>
                    </a>
                </div>
            </div><!-- /.col-lg-12 -->
        </div>

    </div> <!-- /container -->

{% endblock %}